-- This is my autostart config / autostart someone dependencies and apps
local ids = require("Config.Identifiers")
hl.on("hyprland.start", function()
	---@diagnostic disable: undefined-global
	hl.exec_cmd("dbus-update-activation-environment --systemd --all")
	hl.exec_cmd("systemctl --user start --no-block xdg-desktop-portal-hyprland")
	hl.exec_cmd("nm-applet")
	hl.exec_cmd("waybar")
	hl.exec_cmd("swaync")
	ids.set_random_wallpaper()
	hl.exec_cmd(Polkit)
	hl.exec_cmd("discord --start-minimized")
	hl.exec_cmd("easyeffects --gapplication-service")
	hl.exec_cmd("youtube-music")
	hl.exec_cmd("sleep 2 && flatpak run com.github.zocker_160.SyncThingy")
end)
